### ISSUE TITLE
Response serialization of arrays with different object-types not covered

### ISSUE THREAD

**Issue by simon-schubert** [simon-schubert/terry-api#126]
https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/inheritance-mapping.html
Doctrine's DiscriminatorMap functionality is an example, that it could be possible to have different object-types in the same array.

This case is currently not covered by the bundle.

It wouldn't break, but serialization would be skipped.

TBD if it should be supported

https://github.com/violines/rest-bundle/blob/0.x/src/Type/ObjectCollection.php#L50

**Comment by HellPat** [comment]
I think this is not really a "Bug", but instead an unsupported functionality.

If one uses a Discriminator-Column it still returns an array of objects. You could remove [checking for same class](https://github.com/violines/rest-bundle/blob/0.x/src/Type/ObjectCollection.php#L51) at all.

As long as the objects are Serializeable somehow ("Use any property attributes/annotations from symfony/serializer or symfony/validator") it does not matter.

One _should_  add the `discriminator_column` to be serialized and should be done.

**Comment by simon-schubert** [comment]
> If one uses a Discriminator-Column it still returns an array of objects. You could remove [checking for same class](https://github.com/violines/rest-bundle/blob/0.x/src/Type/ObjectCollection.php#L51) at all.
> 

The nice thing about a List is, that it is only necessary to check one of the objects having the `@HttpApi` annotation. Thats why the collection also has a method ->first() and only this object gets checked then by the caller. 

Atm the annotation reads are not cached. 

For 2 annoations per request i think the overhead is neglectable, but if you parse the doc block of a list, that could go into the direction of >1ms
