### ISSUE TITLE
Using Ok::new() in docs is confusing

### ISSUE THREAD

**Issue by HellPat** [simon-schubert/terry-api#128]
You have a class for testing called `Ok`. While I think it's readable, I think it's not good to use it
as an example in the `Readme.md`.

A Symfony-User expects to return a `Response` - you could also use a `@HttpApi`-Object you showed
in the `Readme.md`.

**Comment by simon-schubert** [comment]
hey @HellPat,
very good feedback. I'm gonna see what I can do about it. Or if you have already an Idea, feel free to send a little PR.
