### ISSUE TITLE
Consider using the static code analysis toll to find possible errors

### ISSUE THREAD

**Issue by peter279k** [simon-schubert/terry-api#96]
As title, I think it should be good to integrate static code analysis tool for this repository.

And it can find some error without writing any test codes :-).

They're two possible static code analysis tool can be considered:

- PHPStan
- Psalm

Once this issue is accepted by this repository owner, I'll be happy to work on that.

**Comment by simon-schubert** [comment]
thank you very much. Maybe its not very good organized in workflows yet, but when running composer test, you actually run
- php-cs-fixer
- phpunit
- psalm
- infection

So static analysis is very cool! Psalm is already in use!

**Comment by peter279k** [comment]
Good. Closed because the `Psalm` has been integrated.
